const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), c = [
  a + "/_app/immutable/entry/app.148b2d50.js",
  a + "/_app/immutable/assets/0.b1fb4486.css",
  a + "/_app/immutable/nodes/0.3d8c99c3.js",
  a + "/_app/immutable/nodes/1.0929e7e2.js",
  a + "/_app/immutable/nodes/2.8b1f4f9a.js",
  a + "/_app/immutable/assets/3.5b11e624.css",
  a + "/_app/immutable/nodes/3.aaf5bde7.js",
  a + "/_app/immutable/nodes/4.686ac406.js",
  a + "/_app/immutable/assets/5.c9c22b2a.css",
  a + "/_app/immutable/nodes/5.6f1cccb7.js",
  a + "/_app/immutable/assets/MiscUtils.4f1e9ba5.css",
  a + "/_app/immutable/assets/Renderer.c5358d2e.css",
  a + "/_app/immutable/chunks/MiscUtils.903d68f5.js",
  a + "/_app/immutable/chunks/Renderer.f3ff8eff.js",
  a + "/_app/immutable/chunks/fa.b7c0bbdc.js",
  a + "/_app/immutable/assets/fa.95b16411.css",
  a + "/_app/immutable/chunks/index.16e709dc.js",
  a + "/_app/immutable/chunks/index.db2a9e3f.js",
  a + "/_app/immutable/chunks/index.e248da5c.js",
  a + "/_app/immutable/chunks/preload-helper.41c905a7.js",
  a + "/_app/immutable/chunks/singletons.22f48944.js",
  a + "/_app/immutable/chunks/stores.126ba612.js",
  a + "/_app/immutable/entry/start.6eeaa80c.js",
  a + "/_app/immutable/chunks/ancestry-anadi.3c59ca60.js",
  a + "/_app/immutable/chunks/ancestry-android.3ccc1d76.js",
  a + "/_app/immutable/chunks/ancestry-automaton.7d5a0c09.js",
  a + "/_app/immutable/chunks/ancestry-azarketi.d430a275.js",
  a + "/_app/immutable/chunks/ancestry-catfolk.a8424c1c.js",
  a + "/_app/immutable/chunks/ancestry-conrasu.7b4b29cb.js",
  a + "/_app/immutable/chunks/ancestry-dwarf.42e980c0.js",
  a + "/_app/immutable/chunks/ancestry-elf.51727f8d.js",
  a + "/_app/immutable/chunks/ancestry-fetchling.657108bb.js",
  a + "/_app/immutable/chunks/ancestry-fleshwarp.1e929337.js",
  a + "/_app/immutable/chunks/ancestry-ghoran.2fec682b.js",
  a + "/_app/immutable/chunks/ancestry-gnoll.4f19b092.js",
  a + "/_app/immutable/chunks/ancestry-gnome.6c002b00.js",
  a + "/_app/immutable/chunks/ancestry-goblin.ff1781fd.js",
  a + "/_app/immutable/chunks/ancestry-goloma.8afd49ec.js",
  a + "/_app/immutable/chunks/ancestry-grippli.baaf9d04.js",
  a + "/_app/immutable/chunks/ancestry-halfling.8cf6144e.js",
  a + "/_app/immutable/chunks/ancestry-hobgoblin.c7a481c9.js",
  a + "/_app/immutable/chunks/ancestry-human.95f9f647.js",
  a + "/_app/immutable/chunks/ancestry-kashrishi.acb67d38.js",
  a + "/_app/immutable/chunks/ancestry-kitsune.98276cba.js",
  a + "/_app/immutable/chunks/ancestry-kobold.c9435bfa.js",
  a + "/_app/immutable/chunks/ancestry-leshy.b58a9749.js",
  a + "/_app/immutable/chunks/ancestry-lizardfolk.c99c2340.js",
  a + "/_app/immutable/chunks/ancestry-nagaji.b851a578.js",
  a + "/_app/immutable/chunks/ancestry-orc.3b2085e8.js",
  a + "/_app/immutable/chunks/ancestry-poppet.462486fa.js",
  a + "/_app/immutable/chunks/ancestry-ratfolk.239fb27e.js",
  a + "/_app/immutable/chunks/ancestry-shisk.c3f1579e.js",
  a + "/_app/immutable/chunks/ancestry-shoony.7ab2d4cf.js",
  a + "/_app/immutable/chunks/ancestry-skeleton.b3be2b11.js",
  a + "/_app/immutable/chunks/ancestry-sprite.b4661f75.js",
  a + "/_app/immutable/chunks/ancestry-strix.77c7ea78.js",
  a + "/_app/immutable/chunks/ancestry-tengu.f88c55c5.js",
  a + "/_app/immutable/chunks/ancestry-vanara.9c36c034.js",
  a + "/_app/immutable/chunks/ancestry-vishkanya.95194f50.js"
], i = [
  a + "/fonts/AlbertusMT.ttf",
  a + "/fonts/Basing.ttf",
  a + "/fonts/Blambot-Casual-Regular.ttf",
  a + "/fonts/Convergence-Regular.ttf",
  a + "/fonts/Dax-Regular.ttf",
  a + "/fonts/Dax-bold.ttf",
  a + "/fonts/Gin-Regular.ttf",
  a + "/fonts/OFL.txt",
  a + "/fonts/Pathfinder2eActions.ttf",
  a + "/fonts/Quicksand.ttf",
  a + "/fonts/Roboto-regular.ttf",
  a + "/fonts/Sabon-Bold.ttf",
  a + "/fonts/Sabon-BoldItalic.ttf",
  a + "/fonts/Sabon-Italic.ttf",
  a + "/fonts/Sabon-Roman.ttf",
  a + "/fonts/SabonLTStd-Bold.ttf",
  a + "/fonts/SabonLTStd-BoldItalic.ttf",
  a + "/fonts/SabonLTStd-Italic.ttf",
  a + "/fonts/SabonLTStd-Roman.ttf",
  a + "/fonts/Taroca.ttf",
  a + "/fonts/fa-light-300.eot",
  a + "/fonts/fa-light-300.ttf",
  a + "/fonts/fa-light-300.woff",
  a + "/fonts/fa-light-300.woff2",
  a + "/fonts/fa-regular-400.eot",
  a + "/fonts/fa-regular-400.ttf",
  a + "/fonts/fa-regular-400.woff",
  a + "/fonts/fa-regular-400.woff2",
  a + "/fonts/fa-solid-900.eot",
  a + "/fonts/fa-solid-900.ttf",
  a + "/fonts/fa-solid-900.woff",
  a + "/fonts/fa-solid-900.woff2",
  a + "/fonts/glyphicons-halflings-regular.eot",
  a + "/fonts/glyphicons-halflings-regular.svg",
  a + "/fonts/glyphicons-halflings-regular.ttf",
  a + "/fonts/glyphicons-halflings-regular.woff",
  a + "/fonts/glyphicons-halflings-regular.woff2",
  a + "/fonts/good-pro-400.ttf",
  a + "/fonts/good-pro-400.woff",
  a + "/fonts/good-pro-400.woff2",
  a + "/fonts/good-pro-700.ttf",
  a + "/fonts/good-pro-700.woff",
  a + "/fonts/good-pro-700.woff2",
  a + "/fonts/good-pro-condensed-400.ttf",
  a + "/fonts/good-pro-condensed-400.woff",
  a + "/fonts/good-pro-condensed-700.ttf",
  a + "/fonts/good-pro-condensed-700.woff",
  a + "/fonts/good-pro-condensed-700.woff2",
  a + "/fonts/good-pro-condensed-italic-400.ttf",
  a + "/fonts/good-pro-condensed-italic-400.woff",
  a + "/fonts/good-pro-condensed-italic-700.ttf",
  a + "/fonts/good-pro-condensed-italic-700.woff",
  a + "/fonts/good-pro-condensed-italic-700.woff2",
  a + "/fonts/good-pro-italic-400.ttf",
  a + "/fonts/good-pro-italic-400.woff",
  a + "/fonts/good-pro-italic-400.woff2",
  a + "/fonts/good-pro-italic-700.ttf",
  a + "/fonts/good-pro-italic-700.woff",
  a + "/fonts/good-pro-italic-700.woff2",
  a + "/fonts/languages/CRB/Draconic/Iokharic Bold Italic.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic Bold.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic Italic.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Bold Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Bold.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Alt.ttf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Bold Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Bold.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Stone.ttf",
  a + "/fonts/languages/CRB/Dwarven/Dethek.otf",
  a + "/fonts/languages/CRB/Dwarven/Olde Dethek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Olde Dethek.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 2e.ttf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Bold Italic.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Bold.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Italic.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e.ttf",
  a + "/fonts/languages/CRB/Elven/Espruar 5e.ttf",
  a + "/fonts/languages/CRB/Elven/Olde Espruar.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Bold Italic.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Bold.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Italic.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic.otf",
  a + "/fonts/languages/CRB/Human/Harpers.ttf",
  a + "/fonts/languages/CRB/Human/Olde Thorass.otf",
  a + "/fonts/languages/CRB/Human/Thorass Bold Italic.otf",
  a + "/fonts/languages/CRB/Human/Thorass Bold.otf",
  a + "/fonts/languages/CRB/Human/Thorass Italic.otf",
  a + "/fonts/languages/CRB/Human/Thorass.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Bold Italic.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Bold.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Italic.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad.otf",
  a + "/fonts/languages/CRB/Infernal/Infernal.ttf",
  a + "/icons/Background.svg",
  a + "/icons/NoBackground.svg",
  a + "/icons/safari-pinned-tab.svg",
  a + "/images/AoN.webp"
], u = "1683925724476", f = `cache-${u}`, l = [
  ...c,
  // the app itself
  ...i.filter((t) => !t.startsWith("/data"))
  // everything in `static` but the actual data
];
self.addEventListener("install", (t) => {
  async function n() {
    await (await caches.open(f)).addAll(l);
  }
  t.waitUntil(n());
});
self.addEventListener("activate", (t) => {
  async function n() {
    for (const s of await caches.keys())
      s !== f && await caches.delete(s);
  }
  t.waitUntil(n());
});
self.addEventListener("fetch", (t) => {
  if (t.request.method !== "GET" || !t.request.url.startsWith("http"))
    return;
  async function n() {
    const s = new URL(t.request.url), e = await caches.open(f);
    if (l.includes(s.pathname))
      return e.match(s.pathname);
    try {
      const o = await fetch(t.request);
      return o.status === 200 && e.put(t.request, o.clone()), o;
    } catch {
      return e.match(t.request);
    }
  }
  t.respondWith(n());
});
