const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), c = [
  a + "/_app/immutable/entry/app.3ba1a59a.js",
  a + "/_app/immutable/chunks/0.53df9de2.js",
  a + "/_app/immutable/chunks/1.90740eef.js",
  a + "/_app/immutable/chunks/2.54d0b0c8.js",
  a + "/_app/immutable/chunks/3.44f0336c.js",
  a + "/_app/immutable/chunks/4.e2e8318b.js",
  a + "/_app/immutable/chunks/5.b7201ae2.js",
  a + "/_app/immutable/assets/ProgressBar.4f1e9ba5.css",
  a + "/_app/immutable/assets/Renderer.01cf1ad8.css",
  a + "/_app/immutable/chunks/ProgressBar.svelte_svelte_type_style_lang.71927ef1.js",
  a + "/_app/immutable/chunks/Renderer.5ff91db0.js",
  a + "/_app/immutable/chunks/_page.d1f15dd8.js",
  a + "/_app/immutable/chunks/fa.39e775bc.js",
  a + "/_app/immutable/assets/fa.95b16411.css",
  a + "/_app/immutable/chunks/index.54c581ea.js",
  a + "/_app/immutable/chunks/index.65bfe307.js",
  a + "/_app/immutable/chunks/preload-helper.41c905a7.js",
  a + "/_app/immutable/chunks/singletons.bd37ecde.js",
  a + "/_app/immutable/chunks/stores.b462fa93.js",
  a + "/_app/immutable/entry/start.96825859.js",
  a + "/_app/immutable/entry/error.svelte.050d7396.js",
  a + "/_app/immutable/chunks/ancestry-anadi.fbeb9cbb.js",
  a + "/_app/immutable/chunks/ancestry-android.121e4632.js",
  a + "/_app/immutable/chunks/ancestry-automaton.b9e564f7.js",
  a + "/_app/immutable/chunks/ancestry-azarketi.51ec23f6.js",
  a + "/_app/immutable/chunks/ancestry-catfolk.4822f4f4.js",
  a + "/_app/immutable/chunks/ancestry-conrasu.65200872.js",
  a + "/_app/immutable/chunks/ancestry-dwarf.f21d352f.js",
  a + "/_app/immutable/chunks/ancestry-elf.2a3dcaa0.js",
  a + "/_app/immutable/chunks/ancestry-fetchling.2080607e.js",
  a + "/_app/immutable/chunks/ancestry-fleshwarp.4caf5c3c.js",
  a + "/_app/immutable/chunks/ancestry-ghoran.4b9c8bfb.js",
  a + "/_app/immutable/chunks/ancestry-gnoll.e2b7b93d.js",
  a + "/_app/immutable/chunks/ancestry-gnome.b16db212.js",
  a + "/_app/immutable/chunks/ancestry-goblin.1f21ad7d.js",
  a + "/_app/immutable/chunks/ancestry-goloma.bff16acf.js",
  a + "/_app/immutable/chunks/ancestry-grippli.0660555f.js",
  a + "/_app/immutable/chunks/ancestry-halfling.fd907402.js",
  a + "/_app/immutable/chunks/ancestry-hobgoblin.7da625e9.js",
  a + "/_app/immutable/chunks/ancestry-human.d3c0d3d9.js",
  a + "/_app/immutable/chunks/ancestry-kashrishi.23168fdb.js",
  a + "/_app/immutable/chunks/ancestry-kitsune.9cefc9b8.js",
  a + "/_app/immutable/chunks/ancestry-kobold.3493175b.js",
  a + "/_app/immutable/chunks/ancestry-leshy.bc742b11.js",
  a + "/_app/immutable/chunks/ancestry-lizardfolk.c0f7c7e7.js",
  a + "/_app/immutable/chunks/ancestry-nagaji.1ccc5ae2.js",
  a + "/_app/immutable/chunks/ancestry-orc.98db1654.js",
  a + "/_app/immutable/chunks/ancestry-poppet.5fd4cd8e.js",
  a + "/_app/immutable/chunks/ancestry-ratfolk.38bf5085.js",
  a + "/_app/immutable/chunks/ancestry-shisk.f8091b2b.js",
  a + "/_app/immutable/chunks/ancestry-shoony.2140634d.js",
  a + "/_app/immutable/chunks/ancestry-skeleton.88864c27.js",
  a + "/_app/immutable/chunks/ancestry-sprite.fbe7645a.js",
  a + "/_app/immutable/chunks/ancestry-strix.9fbd5e31.js",
  a + "/_app/immutable/chunks/ancestry-tengu.8cc46df0.js",
  a + "/_app/immutable/chunks/ancestry-vanara.76fa06e7.js",
  a + "/_app/immutable/chunks/ancestry-vishkanya.97fce2f2.js",
  a + "/_app/immutable/assets/_layout.cab19389.css",
  a + "/_app/immutable/entry/_layout.svelte.dd564d5d.js",
  a + "/_app/immutable/entry/_page.svelte.72793bcd.js",
  a + "/_app/immutable/assets/_page.d65040e7.css",
  a + "/_app/immutable/entry/ancestries-page.js.26120dbe.js",
  a + "/_app/immutable/entry/ancestries-page.svelte.2d674ee4.js",
  a + "/_app/immutable/entry/licenses-page.svelte.3d083e94.js",
  a + "/_app/immutable/assets/_page.c9c22b2a.css",
  a + "/_app/immutable/entry/renderer-page.svelte.ade40e7f.js"
], r = [
  a + "/fonts/AlbertusMT.ttf",
  a + "/fonts/Basing.ttf",
  a + "/fonts/Blambot-Casual-Regular.ttf",
  a + "/fonts/Convergence-Regular.ttf",
  a + "/fonts/Dax-Regular.ttf",
  a + "/fonts/Dax-bold.ttf",
  a + "/fonts/Gin-Regular.ttf",
  a + "/fonts/OFL.txt",
  a + "/fonts/Pathfinder2eActions.ttf",
  a + "/fonts/Quicksand.ttf",
  a + "/fonts/Roboto-regular.ttf",
  a + "/fonts/Sabon-Bold.ttf",
  a + "/fonts/Sabon-BoldItalic.ttf",
  a + "/fonts/Sabon-Italic.ttf",
  a + "/fonts/Sabon-Roman.ttf",
  a + "/fonts/SabonLTStd-Bold.ttf",
  a + "/fonts/SabonLTStd-BoldItalic.ttf",
  a + "/fonts/SabonLTStd-Italic.ttf",
  a + "/fonts/SabonLTStd-Roman.ttf",
  a + "/fonts/Taroca.ttf",
  a + "/fonts/fa-light-300.eot",
  a + "/fonts/fa-light-300.ttf",
  a + "/fonts/fa-light-300.woff",
  a + "/fonts/fa-light-300.woff2",
  a + "/fonts/fa-regular-400.eot",
  a + "/fonts/fa-regular-400.ttf",
  a + "/fonts/fa-regular-400.woff",
  a + "/fonts/fa-regular-400.woff2",
  a + "/fonts/fa-solid-900.eot",
  a + "/fonts/fa-solid-900.ttf",
  a + "/fonts/fa-solid-900.woff",
  a + "/fonts/fa-solid-900.woff2",
  a + "/fonts/glyphicons-halflings-regular.eot",
  a + "/fonts/glyphicons-halflings-regular.svg",
  a + "/fonts/glyphicons-halflings-regular.ttf",
  a + "/fonts/glyphicons-halflings-regular.woff",
  a + "/fonts/glyphicons-halflings-regular.woff2",
  a + "/fonts/good-pro-400.ttf",
  a + "/fonts/good-pro-400.woff",
  a + "/fonts/good-pro-400.woff2",
  a + "/fonts/good-pro-700.ttf",
  a + "/fonts/good-pro-700.woff",
  a + "/fonts/good-pro-700.woff2",
  a + "/fonts/good-pro-condensed-400.ttf",
  a + "/fonts/good-pro-condensed-400.woff",
  a + "/fonts/good-pro-condensed-700.ttf",
  a + "/fonts/good-pro-condensed-700.woff",
  a + "/fonts/good-pro-condensed-700.woff2",
  a + "/fonts/good-pro-condensed-italic-400.ttf",
  a + "/fonts/good-pro-condensed-italic-400.woff",
  a + "/fonts/good-pro-condensed-italic-700.ttf",
  a + "/fonts/good-pro-condensed-italic-700.woff",
  a + "/fonts/good-pro-condensed-italic-700.woff2",
  a + "/fonts/good-pro-italic-400.ttf",
  a + "/fonts/good-pro-italic-400.woff",
  a + "/fonts/good-pro-italic-400.woff2",
  a + "/fonts/good-pro-italic-700.ttf",
  a + "/fonts/good-pro-italic-700.woff",
  a + "/fonts/good-pro-italic-700.woff2",
  a + "/fonts/languages/CRB/Draconic/Iokharic Bold Italic.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic Bold.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic Italic.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Bold Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Bold.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Alt.ttf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Bold Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Bold.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Stone.ttf",
  a + "/fonts/languages/CRB/Dwarven/Dethek.otf",
  a + "/fonts/languages/CRB/Dwarven/Olde Dethek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Olde Dethek.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 2e.ttf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Bold Italic.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Bold.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Italic.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e.ttf",
  a + "/fonts/languages/CRB/Elven/Espruar 5e.ttf",
  a + "/fonts/languages/CRB/Elven/Olde Espruar.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Bold Italic.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Bold.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Italic.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic.otf",
  a + "/fonts/languages/CRB/Human/Harpers.ttf",
  a + "/fonts/languages/CRB/Human/Olde Thorass.otf",
  a + "/fonts/languages/CRB/Human/Thorass Bold Italic.otf",
  a + "/fonts/languages/CRB/Human/Thorass Bold.otf",
  a + "/fonts/languages/CRB/Human/Thorass Italic.otf",
  a + "/fonts/languages/CRB/Human/Thorass.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Bold Italic.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Bold.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Italic.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad.otf",
  a + "/fonts/languages/CRB/Infernal/Infernal.ttf",
  a + "/icons/Background.svg",
  a + "/icons/NoBackground.svg",
  a + "/icons/safari-pinned-tab.svg"
], u = "1683408968286", f = `cache-${u}`, l = [
  ...c,
  // the app itself
  ...r.filter((t) => !t.startsWith("/data"))
  // everything in `static` but the actual data
];
self.addEventListener("install", (t) => {
  async function e() {
    await (await caches.open(f)).addAll(l);
  }
  t.waitUntil(e());
});
self.addEventListener("activate", (t) => {
  async function e() {
    for (const s of await caches.keys())
      s !== f && await caches.delete(s);
  }
  t.waitUntil(e());
});
self.addEventListener("fetch", (t) => {
  if (t.request.method !== "GET" || !t.request.url.startsWith("http"))
    return;
  async function e() {
    const s = new URL(t.request.url), n = await caches.open(f);
    if (l.includes(s.pathname))
      return n.match(s.pathname);
    try {
      const o = await fetch(t.request);
      return o.status === 200 && n.put(t.request, o.clone()), o;
    } catch {
      return n.match(t.request);
    }
  }
  t.respondWith(e());
});
