const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), c = [
  a + "/_app/immutable/entry/app.80711d7e.js",
  a + "/_app/immutable/assets/0.f6b52dde.css",
  a + "/_app/immutable/nodes/0.8d40b84b.js",
  a + "/_app/immutable/nodes/1.a17a40a7.js",
  a + "/_app/immutable/nodes/2.8b1f4f9a.js",
  a + "/_app/immutable/assets/3.5b11e624.css",
  a + "/_app/immutable/nodes/3.d8915fe6.js",
  a + "/_app/immutable/nodes/4.81873bcf.js",
  a + "/_app/immutable/assets/5.c9c22b2a.css",
  a + "/_app/immutable/nodes/5.d08b2e99.js",
  a + "/_app/immutable/assets/MiscUtils.a5e346fc.css",
  a + "/_app/immutable/assets/Renderer.0c343dc9.css",
  a + "/_app/immutable/chunks/MiscUtils.214bafd8.js",
  a + "/_app/immutable/chunks/Renderer.db1592bf.js",
  a + "/_app/immutable/chunks/index.16e709dc.js",
  a + "/_app/immutable/chunks/index.db2a9e3f.js",
  a + "/_app/immutable/chunks/index.e248da5c.js",
  a + "/_app/immutable/chunks/preload-helper.41c905a7.js",
  a + "/_app/immutable/chunks/singletons.5011e9b1.js",
  a + "/_app/immutable/chunks/stores.f98cc71a.js",
  a + "/_app/immutable/entry/start.18d79639.js",
  a + "/_app/immutable/chunks/ancestry-anadi.c7960efb.js",
  a + "/_app/immutable/chunks/ancestry-android.22dcb6be.js",
  a + "/_app/immutable/chunks/ancestry-automaton.fee60d93.js",
  a + "/_app/immutable/chunks/ancestry-azarketi.3b917f28.js",
  a + "/_app/immutable/chunks/ancestry-catfolk.bd5045af.js",
  a + "/_app/immutable/chunks/ancestry-conrasu.da2e4c50.js",
  a + "/_app/immutable/chunks/ancestry-dwarf.a9c56490.js",
  a + "/_app/immutable/chunks/ancestry-elf.a6be3b57.js",
  a + "/_app/immutable/chunks/ancestry-fetchling.e33e9008.js",
  a + "/_app/immutable/chunks/ancestry-fleshwarp.595602f6.js",
  a + "/_app/immutable/chunks/ancestry-ghoran.6df40ca1.js",
  a + "/_app/immutable/chunks/ancestry-gnoll.126cb3ed.js",
  a + "/_app/immutable/chunks/ancestry-gnome.29e51bc5.js",
  a + "/_app/immutable/chunks/ancestry-goblin.20b6d1cf.js",
  a + "/_app/immutable/chunks/ancestry-goloma.dd6e3190.js",
  a + "/_app/immutable/chunks/ancestry-grippli.fdaff84b.js",
  a + "/_app/immutable/chunks/ancestry-halfling.869fea2a.js",
  a + "/_app/immutable/chunks/ancestry-hobgoblin.1982cdf8.js",
  a + "/_app/immutable/chunks/ancestry-human.c6d51bf9.js",
  a + "/_app/immutable/chunks/ancestry-kashrishi.d4a79401.js",
  a + "/_app/immutable/chunks/ancestry-kitsune.7a0d21b9.js",
  a + "/_app/immutable/chunks/ancestry-kobold.943b8121.js",
  a + "/_app/immutable/chunks/ancestry-leshy.4488d032.js",
  a + "/_app/immutable/chunks/ancestry-lizardfolk.838c0136.js",
  a + "/_app/immutable/chunks/ancestry-nagaji.4695cdf8.js",
  a + "/_app/immutable/chunks/ancestry-orc.0dc73a51.js",
  a + "/_app/immutable/chunks/ancestry-poppet.65e96566.js",
  a + "/_app/immutable/chunks/ancestry-ratfolk.4edfccc8.js",
  a + "/_app/immutable/chunks/ancestry-shisk.454bc4c6.js",
  a + "/_app/immutable/chunks/ancestry-shoony.4507cf60.js",
  a + "/_app/immutable/chunks/ancestry-skeleton.e21ad147.js",
  a + "/_app/immutable/chunks/ancestry-sprite.e86541d9.js",
  a + "/_app/immutable/chunks/ancestry-strix.41a15f4b.js",
  a + "/_app/immutable/chunks/ancestry-tengu.d6b302cb.js",
  a + "/_app/immutable/chunks/ancestry-vanara.f23f4f4a.js",
  a + "/_app/immutable/chunks/ancestry-vishkanya.7c187811.js"
], i = [
  a + "/fonts/AlbertusMT.ttf",
  a + "/fonts/Basing.ttf",
  a + "/fonts/Blambot-Casual-Regular.ttf",
  a + "/fonts/Convergence-Regular.ttf",
  a + "/fonts/Dax-Regular.ttf",
  a + "/fonts/Dax-bold.ttf",
  a + "/fonts/Gin-Regular.ttf",
  a + "/fonts/OFL.txt",
  a + "/fonts/Pathfinder2eActions.ttf",
  a + "/fonts/Quicksand.ttf",
  a + "/fonts/Roboto-regular.ttf",
  a + "/fonts/Sabon-Bold.ttf",
  a + "/fonts/Sabon-BoldItalic.ttf",
  a + "/fonts/Sabon-Italic.ttf",
  a + "/fonts/Sabon-Roman.ttf",
  a + "/fonts/SabonLTStd-Bold.ttf",
  a + "/fonts/SabonLTStd-BoldItalic.ttf",
  a + "/fonts/SabonLTStd-Italic.ttf",
  a + "/fonts/SabonLTStd-Roman.ttf",
  a + "/fonts/Taroca.ttf",
  a + "/fonts/fa-light-300.eot",
  a + "/fonts/fa-light-300.ttf",
  a + "/fonts/fa-light-300.woff",
  a + "/fonts/fa-light-300.woff2",
  a + "/fonts/fa-regular-400.eot",
  a + "/fonts/fa-regular-400.ttf",
  a + "/fonts/fa-regular-400.woff",
  a + "/fonts/fa-regular-400.woff2",
  a + "/fonts/fa-solid-900.eot",
  a + "/fonts/fa-solid-900.ttf",
  a + "/fonts/fa-solid-900.woff",
  a + "/fonts/fa-solid-900.woff2",
  a + "/fonts/glyphicons-halflings-regular.eot",
  a + "/fonts/glyphicons-halflings-regular.svg",
  a + "/fonts/glyphicons-halflings-regular.ttf",
  a + "/fonts/glyphicons-halflings-regular.woff",
  a + "/fonts/glyphicons-halflings-regular.woff2",
  a + "/fonts/good-pro-400.ttf",
  a + "/fonts/good-pro-400.woff",
  a + "/fonts/good-pro-400.woff2",
  a + "/fonts/good-pro-700.ttf",
  a + "/fonts/good-pro-700.woff",
  a + "/fonts/good-pro-700.woff2",
  a + "/fonts/good-pro-condensed-400.ttf",
  a + "/fonts/good-pro-condensed-400.woff",
  a + "/fonts/good-pro-condensed-700.ttf",
  a + "/fonts/good-pro-condensed-700.woff",
  a + "/fonts/good-pro-condensed-700.woff2",
  a + "/fonts/good-pro-condensed-italic-400.ttf",
  a + "/fonts/good-pro-condensed-italic-400.woff",
  a + "/fonts/good-pro-condensed-italic-700.ttf",
  a + "/fonts/good-pro-condensed-italic-700.woff",
  a + "/fonts/good-pro-condensed-italic-700.woff2",
  a + "/fonts/good-pro-italic-400.ttf",
  a + "/fonts/good-pro-italic-400.woff",
  a + "/fonts/good-pro-italic-400.woff2",
  a + "/fonts/good-pro-italic-700.ttf",
  a + "/fonts/good-pro-italic-700.woff",
  a + "/fonts/good-pro-italic-700.woff2",
  a + "/fonts/languages/CRB/Draconic/Iokharic Bold Italic.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic Bold.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic Italic.otf",
  a + "/fonts/languages/CRB/Draconic/Iokharic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Bold Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Bold.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Davek.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Alt.ttf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Bold Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Bold.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Dethek Stone.ttf",
  a + "/fonts/languages/CRB/Dwarven/Dethek.otf",
  a + "/fonts/languages/CRB/Dwarven/Olde Dethek Italic.otf",
  a + "/fonts/languages/CRB/Dwarven/Olde Dethek.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 2e.ttf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Bold Italic.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Bold.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e Italic.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e.otf",
  a + "/fonts/languages/CRB/Elven/Espruar 3e.ttf",
  a + "/fonts/languages/CRB/Elven/Espruar 5e.ttf",
  a + "/fonts/languages/CRB/Elven/Olde Espruar.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Bold Italic.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Bold.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic Italic.otf",
  a + "/fonts/languages/CRB/Elven/Rellanic.otf",
  a + "/fonts/languages/CRB/Human/Harpers.ttf",
  a + "/fonts/languages/CRB/Human/Olde Thorass.otf",
  a + "/fonts/languages/CRB/Human/Thorass Bold Italic.otf",
  a + "/fonts/languages/CRB/Human/Thorass Bold.otf",
  a + "/fonts/languages/CRB/Human/Thorass Italic.otf",
  a + "/fonts/languages/CRB/Human/Thorass.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Bold Italic.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Bold.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad Italic.otf",
  a + "/fonts/languages/CRB/Infernal/Barazhad.otf",
  a + "/fonts/languages/CRB/Infernal/Infernal.ttf",
  a + "/icons/Background.svg",
  a + "/icons/NoBackground.svg",
  a + "/icons/safari-pinned-tab.svg",
  a + "/images/AoN.webp"
], u = "1684008837099", f = `cache-${u}`, l = [
  ...c,
  // the app itself
  ...i.filter((t) => !t.startsWith("/data"))
  // everything in `static` but the actual data
];
self.addEventListener("install", (t) => {
  async function n() {
    await (await caches.open(f)).addAll(l);
  }
  t.waitUntil(n());
});
self.addEventListener("activate", (t) => {
  async function n() {
    for (const s of await caches.keys())
      s !== f && await caches.delete(s);
  }
  t.waitUntil(n());
});
self.addEventListener("fetch", (t) => {
  if (t.request.method !== "GET" || !t.request.url.startsWith("http"))
    return;
  async function n() {
    const s = new URL(t.request.url), e = await caches.open(f);
    if (l.includes(s.pathname))
      return e.match(s.pathname);
    try {
      const o = await fetch(t.request);
      return o.status === 200 && e.put(t.request, o.clone()), o;
    } catch {
      return e.match(t.request);
    }
  }
  t.respondWith(n());
});
