name: Tests
on:
    pull_request:
    push:

jobs:
    playwright:
        # https://github.com/orgs/community/discussions/26786
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && !contains( github.event.head_commit.message, 'Merge pull request')) }}
        name: Playwright Tests
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - run: npm ci

            - run: npx playwright install --with-deps
            - run: npx playwright install-deps
            - run: npx playwright install

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm run test

            - name: Upload test failure results
              if: failure()
              uses: actions/upload-artifact@v3
              with:
                  name: playwright-report
                  path: test-results
